services:
  web-flasher:
    container_name: loconetoverthread
    build:
      context: ./web-flasher
      dockerfile: Dockerfile
    ports:
      - "${WEB_FLASHER_PORT:-8080}:80"
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true
