set(LNOT_FIRMWARE_VERSION "$ENV{LNOT_FIRMWARE_VERSION}")

if(LNOT_FIRMWARE_VERSION STREQUAL "")
    string(TIMESTAMP LNOT_BUILD_DATE "%y%m%d" UTC)
    set(PROJECT_VER "v0.0.${LNOT_BUILD_DATE}.0")
elseif(NOT LNOT_FIRMWARE_VERSION MATCHES "^v[0-9]+\\.[0-9]+\\.[0-9][0-9][0-9][0-9][0-9][0-9]\\.[0-9]+$")
    message(FATAL_ERROR
        "LNOT_FIRMWARE_VERSION must use vMAJOR.MINOR.YYMMDD.RR.")
else()
    set(PROJECT_VER "${LNOT_FIRMWARE_VERSION}")
endif()
